<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Anime;

class AnimeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $animes = [
            // Trending/Popular Anime (15 records)
            [
                'title' => 'ดาบพิฆาตอสูร',
                'description' => 'เด็กชายกลายเป็นนักล่าอสูรเพื่อช่วยน้องสาวและแก้แค้นครอบครัว',
                'release_date' => '2019-04-06',
                'rating' => 9.2,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'โจมตียักษ์',
                'description' => 'มนุษยชาติต่อสู้เพื่อความอยู่รอดกับยักษ์ไททัน',
                'release_date' => '2013-04-07',
                'rating' => 9.0,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ฮีโร่แอคคาเดเมีย',
                'description' => 'เด็กชายที่ไม่มีพลังพิเศษในโลกที่เต็มไปด้วยฮีโร่ฝันจะเป็นฮีโร่',
                'release_date' => '2016-04-03',
                'rating' => 8.7,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'จูจุตสึไคเซ็น',
                'description' => 'เด็กชายกลืนเครื่องรางต้องคำผูกมัดและมีส่วนเกี่ยวข้องกับโลกของหมอผี',
                'release_date' => '2020-10-03',
                'rating' => 8.9,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'วันพีซ',
                'description' => 'กัปตันโจรสลัดและลูกเรือของเขาค้นหาสมบัติสูงสุด',
                'release_date' => '1999-10-20',
                'rating' => 9.1,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'นารูโตะ',
                'description' => 'นินจาหนุ่มแสวงหาความยอมรับและมีความฝันจะเป็นโฮคาเงะ',
                'release_date' => '2002-10-03',
                'rating' => 8.5,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ฟูลเมทัล อัลเคมิสต์',
                'description' => 'พี่น้องสองคนออกตามหาศิลาอาคมเพื่อฟื้นคืนร่างของพวกเขา',
                'release_date' => '2003-10-04',
                'rating' => 9.3,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'เดธ โน้ต',
                'description' => 'นักเรียนใช้สมุดบันทึกเหนือธรรมชาติในการฆ่าอาชญากร',
                'release_date' => '2006-10-03',
                'rating' => 9.0,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'สปาย x แฟมิลี่',
                'description' => 'สายลับสร้างครอบครัวปลอมเพื่อทำภารกิจ',
                'release_date' => '2022-04-09',
                'rating' => 8.8,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ดemon สเลเยอร์: Entertainment District',
                'description' => 'เทนจิโร่และเพื่อน ๆ เดินทางไปยังย่านบันเทิง',
                'release_date' => '2021-12-05',
                'rating' => 8.9,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'มือที่มองไม่เห็น',
                'description' => 'เด็กผู้ชายที่สามารถสัมผัสวิญญาณได้ต่อสู้กับภูตผี',
                'release_date' => '2004-10-04',
                'rating' => 8.6,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'มังกรบอล',
                'description' => 'กุโอกุใช้พลังจักรวาลเพื่อตามหางลูกบอลดาว',
                'release_date' => '1986-02-26',
                'rating' => 8.7,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'วิ่งซ์',
                'description' => 'ซาวาโระต้องการเป็นนักวิ่งที่เร็วที่สุดในโลก',
                'release_date' => '2016-07-03',
                'rating' => 8.4,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ดิวเคลียด',
                'description' => 'ทหารในสงครามโลกครั้งที่สองต่อสู้กับซอมบี้',
                'release_date' => '2004-07-05',
                'rating' => 8.3,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ดิวเคลียด ซีซั่น 2',
                'description' => 'ภาคต่อของดิวเคลียดที่มีชื่อว่าบลูมี่',
                'release_date' => '2005-07-04',
                'rating' => 8.5,
                'is_trending' => true,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Additional Anime (15 records)
            [
                'title' => 'โคด้า',
                'description' => 'เด็กชายมีชีวิตคู่ขนานกับสัตว์ป่า',
                'release_date' => '2000-04-05',
                'rating' => 8.2,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'มังกรบอล GT',
                'description' => 'ภาคต่อของมังกรบอลที่เด็กกลายเป็นผู้ใหญ่',
                'release_date' => '1996-02-07',
                'rating' => 8.1,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'นารูโตะ ชิปปูเด็น',
                'description' => 'ภาคต่อของนารูโตะที่เน้นตัวละครใหม่',
                'release_date' => '2007-02-15',
                'rating' => 8.4,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'วิ่งซ์ นิวเจเนอเรชั่น',
                'description' => 'รุ่นใหม่ของวิ่งซ์ที่มีตัวละครใหม่',
                'release_date' => '2018-10-07',
                'rating' => 8.1,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'โจมตียักษ์: ซีซั่น 2',
                'description' => 'ภาคต่อของโจมตียักษ์ที่สำรวจเมืองนอก',
                'release_date' => '2017-04-01',
                'rating' => 8.8,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'โจมตียักษ์: ซีซั่น 3',
                'description' => 'ภาคต่อที่สำรวจประวัติศาสตร์ของไททัน',
                'release_date' => '2018-07-22',
                'rating' => 9.1,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'โจมตียักษ์: ฟินัลซีซั่น',
                'description' => 'ภาคสุดท้ายของซีรีส์โจมตียักษ์',
                'release_date' => '2020-12-06',
                'rating' => 8.9,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ฮีโร่แอคคาเดเมีย ซีซั่น 2',
                'description' => 'ภาคต่อที่เด็กฝึกฝนเพื่อเป็นฮีโร่',
                'release_date' => '2017-04-01',
                'rating' => 8.6,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ฮีโร่แอคคาเดเมีย ซีซั่น 3',
                'description' => 'ภาคที่สำรวจอดีตของวิลเลน',
                'release_date' => '2018-04-07',
                'rating' => 8.8,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ฮีโร่แอคคาเดเมีย ซีซั่น 4',
                'description' => 'ภาคที่ต่อสู้กับเชสต์',
                'release_date' => '2019-10-12',
                'rating' => 8.5,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ดาบพิฆาตอสูร: ซีซั่น 2',
                'description' => 'ภาคต่อที่ต่อสู้กับอสูรสายเลือด',
                'release_date' => '2021-10-10',
                'rating' => 9.0,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ดาบพิฆาตอสูร: ซีซั่น 3',
                'description' => 'ภาคสุดท้ายที่ต่อสู้กับมูซาน',
                'release_date' => '2023-04-09',
                'rating' => 9.1,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'จูจุตสึไคเซ็น ซีซั่น 2',
                'description' => 'ภาคต่อที่ต่อสู้กับคิง',
                'release_date' => '2023-07-06',
                'rating' => 8.8,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'สปาย x แฟมิลี่ ซีซั่น 2',
                'description' => 'ภาคต่อของครอบครัวฟอร์เจอร์',
                'release_date' => '2023-10-07',
                'rating' => 8.7,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'มือที่มองไม่เห็น ซีซั่น 2',
                'description' => 'ภาคต่อที่ต่อสู้กับภูตผีระดับสูง',
                'release_date' => '2005-04-02',
                'rating' => 8.4,
                'is_trending' => false,
                'image_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Anime::insert($animes);
    }
}